language: node_js
node_js:
- '5.0.0'
install:
- npm install
services: mongodb
env:
  global:
    - export TWILIO_ACCOUNT_SID=Your-Account-SID
    - export TWILIO_AUTH_TOKEN=Your-Twilio-Authy-Token
    - export TWILIO_APP_SID=Your-Twilio-APP-SID
    - export TWILIO_PHONE_NUMBER=Your-Twilio-Phone-Number
